# This is a pipeline that rebuilds a model, then uploads the resultant
# model files and .PDF and other reports as (buildkite, not Julia) artifacts.

steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner:
          # This will create one job per file
          watch:
            - path: benchmarks/.*\.jmd
          path_processor: per-file
          target: .buildkite/coalescer/rebuild_models
          target_type: template
      - staticfloat/forerunner:
          # This will create one job overall, throwing all path information away
          watch:
            - path: src/*.*.jl
            - path: .*\\.toml
          target: .buildkite/test_sciml.yml
  - label: ":hammer: ${MODEL}"
    plugins:
      # Install Julia
      - JuliaCI/julia#v1:
          version: 1.6
    timeout_in_minutes: 60
    commands:
      # Instantiate current project
      - echo "--- Instantiate Project"
      - julia --project=. .buildkite/commands/instantiate.jl
      # Rebuild the given model
      - echo "+++ Build {MODEL}"
      - julia --project=. .buildkite/commands/rebuild_models.jl {MODEL}
      - MODEL_NAME=${MODEL%.*}
    artifact_paths:
      # Upload .html
      - "html/${MODEL_NAME}*.html"
      # Upload markdown
      - "markdown/${MODEL_NAME}*.md"
      # Upload notebook
      - "notebook/${MODEL_NAME}*.ipynb"
      # Upload .pdf files
      - "pdf/${MODEL_NAME}.pdf"
      # Upload Julia script
      - "script/${MODEL_NAME}*.jl"