# This is a pipeline that runs the test of SciMLBenchmarks
env:
  # We isolate ourselves from the rest of the system by using
  # a completely separate depot; ensuring more hermetic builds
  JULIA_DEPOT_PATH: ${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite/.depot

steps:
  - label: ":julia: SciML tests"
    plugins:
      # Install Julia
      - JuliaCI/julia#4404e63cf3f95464ddb89defba5d549c838447c4:
          version: "1.6"
          clone_registry: false
    commands:
      # Instantiate current project
      - echo "--- Instantiate Project"
      - julia --project=. .buildkite/commands/instantiate.jl
      # Build the given surrogate
      - echo "+++ Run tests"
      - julia --project=. test/runtests.jl
    # Allow `[skip tests]` in a commit message to disable this
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60